### ISSUE TITLE
Navigation problem

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/constructzine#17]
Meniul de responsive nu afisaza toate paginile decat dupa refresh

**Comment by rodica-andronache** [comment]
@cristian-ungureanu ai rezolvat problema asta, dar mai ramane ce ti-am zis, cu textele care se suprapun atunci cand sunt mai lungi http://prntscr.com/5p66cl.
Aici poti vb cu Claudiu sa-l intrebi cum e mai bine sa faci

**Comment by ineagu** [comment]
@rodica-andronache @cristian-ungureanu vad ca fonturile nu sunt la fel ca la lite si parca a fost commit pe dev nu ? 

http://dev2.themeisle.com/constructzine/ vs http://dev2.themeisle.com/constructzine-lite/

**Comment by rodica-andronache** [comment]
@cristian-ungureanu tot mai sunt probleme aici . De ex. http://dev2.themeisle.com/constructzine/ daca faci resize ferestrei, de la meniu pe mobil, spre desktop nu mai merge dropdown-ul. Si nu ai rezolvat nici problema cu textele care se suprapun atunci cand sunt mai lungi http://prntscr.com/5p66cl. Mi se pare ca te-ai complicat foarte tare :) ai putea sa-l rogi pe @claudiuvertistudio sa te ajute.
